#!/usr/bin/env bash
# Refresh the vendored ai-dev-kit databricks-skills/ tree at a pinned tag.
#
# Usage:
#   scripts/sync_databricks_skills.sh                 # uses the tag in SKILLS_VERSION
#   scripts/sync_databricks_skills.sh --tag v0.1.12   # bump to a new tag
#   scripts/sync_databricks_skills.sh --tag main      # track latest main (NOT recommended for releases)
#
# What it does:
#   1. shallow-clones databricks-solutions/ai-dev-kit at the requested ref into /tmp
#   2. rsyncs databricks-skills/ into app/seeds/skills/databricks/
#      (excluding the upstream installer scripts that are irrelevant at agent runtime)
#   3. refreshes UPSTREAM_LICENSE.md / UPSTREAM_NOTICE.md / UPSTREAM_NOTICE.txt
#   4. regenerates SKILLS_VERSION with the resolved commit SHA + tag + date
#   5. regenerates INDEX.md (one line per SKILL.md, harvested from the description: field)
#
# Files that are NEVER overwritten by this script:
#   - VENDOR_README.md       (our wrapper README explaining license + modification rules)
#
# After running, review the diff with `git diff app/seeds/skills/databricks/` and
# commit the refresh in its own change so the upstream pin is clearly auditable.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SEED_DIR="$ROOT_DIR/app/seeds/skills/databricks"
TMP_DIR="$(mktemp -d -t ai-dev-kit-sync.XXXXXX)"
trap 'rm -rf "$TMP_DIR"' EXIT

UPSTREAM_URL="https://github.com/databricks-solutions/ai-dev-kit.git"

resolve_pinned_tag() {
  if [[ -f "$SEED_DIR/SKILLS_VERSION" ]]; then
    awk -F': *' '$1=="tag" {print $2; exit}' "$SEED_DIR/SKILLS_VERSION"
  fi
}

REF=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --tag)
      REF="${2:-}"
      shift 2
      ;;
    -h|--help)
      sed -n '2,22p' "$0"
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      exit 2
      ;;
  esac
done

if [[ -z "$REF" ]]; then
  REF="$(resolve_pinned_tag || true)"
fi
if [[ -z "$REF" ]]; then
  echo "no upstream ref given and SKILLS_VERSION is missing a 'tag:' line; pass --tag <ref>" >&2
  exit 2
fi

echo "==> cloning $UPSTREAM_URL at $REF into $TMP_DIR"
git clone --depth 1 --branch "$REF" "$UPSTREAM_URL" "$TMP_DIR/ai-dev-kit" >/dev/null

UPSTREAM_SHA="$(git -C "$TMP_DIR/ai-dev-kit" rev-parse HEAD)"
TODAY="$(date -u +%Y-%m-%d)"

if [[ ! -d "$TMP_DIR/ai-dev-kit/databricks-skills" ]]; then
  echo "upstream ref $REF has no databricks-skills/ directory" >&2
  exit 3
fi

mkdir -p "$SEED_DIR"

echo "==> rsyncing databricks-skills/ into $SEED_DIR"
rsync -a \
  --delete \
  --exclude='install_skills.sh' \
  --exclude='install_genie_code_skills.py' \
  --exclude='VENDOR_README.md' \
  --exclude='SKILLS_VERSION' \
  --exclude='INDEX.md' \
  --exclude='UPSTREAM_LICENSE.md' \
  --exclude='UPSTREAM_NOTICE.md' \
  --exclude='UPSTREAM_NOTICE.txt' \
  "$TMP_DIR/ai-dev-kit/databricks-skills/" \
  "$SEED_DIR/"

echo "==> refreshing UPSTREAM_LICENSE.md / UPSTREAM_NOTICE.md / UPSTREAM_NOTICE.txt"
cp "$TMP_DIR/ai-dev-kit/LICENSE.md" "$SEED_DIR/UPSTREAM_LICENSE.md"
cp "$TMP_DIR/ai-dev-kit/NOTICE.md"  "$SEED_DIR/UPSTREAM_NOTICE.md"
cp "$TMP_DIR/ai-dev-kit/NOTICE.txt" "$SEED_DIR/UPSTREAM_NOTICE.txt"

echo "==> writing SKILLS_VERSION"
cat > "$SEED_DIR/SKILLS_VERSION" <<EOF
upstream: databricks-solutions/ai-dev-kit
tag: $REF
commit: $UPSTREAM_SHA
vendored_at: $TODAY
license: app/seeds/skills/databricks/UPSTREAM_LICENSE.md
notice: app/seeds/skills/databricks/UPSTREAM_NOTICE.txt
scope: databricks-skills/ markdown subtree only (no databricks-tools-core, databricks-mcp-server, databricks-builder-app)
excluded:
  - install_skills.sh           # upstream installer, not needed at agent runtime
  - install_genie_code_skills.py # upstream installer, not needed at agent runtime
modifications: none
EOF

echo "==> regenerating INDEX.md"
python3 - "$SEED_DIR" <<'PYTHON'
import pathlib, re, sys

root = pathlib.Path(sys.argv[1])
header = (
    "# Trevor's Databricks skills (vendored from ai-dev-kit)\n\n"
    "Auto-generated by `scripts/sync_databricks_skills.sh`. Do not edit by hand.\n"
    "Each row summarises a vendored SKILL.md so `skill_search` can route to the\n"
    "right playbook cheaply.\n\n"
    "| Skill | Description |\n"
    "| --- | --- |\n"
)
rows = []
for skill in sorted(root.glob("*/SKILL.md")):
    text = skill.read_text(encoding="utf-8")
    m = re.search(r"^---\s*\n(.*?)\n---", text, re.DOTALL | re.MULTILINE)
    if not m:
        continue
    fm = m.group(1)
    dm = re.search(
        r"^description:\s*(.*?)(?=^[a-zA-Z_]+:|\Z)",
        fm,
        re.DOTALL | re.MULTILINE,
    )
    if not dm:
        desc = "(no description)"
    else:
        raw = dm.group(1).rstrip()
        if raw.lstrip().startswith((">-", ">", "|-", "|")):
            indicator, _, rest = raw.partition("\n")
            joiner = " " if indicator.strip() in (">", ">-") else "\n"
            desc = joiner.join(
                line.strip() for line in rest.splitlines() if line.strip()
            )
        else:
            desc = raw.strip().strip('"')
        desc = re.sub(r"\s+", " ", desc).strip().replace("|", "\\|")
    rows.append(f"| `{skill.parent.name}` | {desc} |")
(root / "INDEX.md").write_text(header + "\n".join(rows) + "\n")
print(f"wrote {len(rows)} rows")
PYTHON

echo "==> done"
echo "    pinned: $REF ($UPSTREAM_SHA)"
echo "    review: git diff app/seeds/skills/databricks/"
